---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: "Emily S. Bellis (n&eacute;e Weiss)"

jobtitle: "Assistant Professor of Bioinformatics"
department: "Department of Computer Science"
address: "Arkansas State University, Jonesboro, AR"
fontawesome: yes
email: ebellis@astate.edu
github: em-bellis
phone: "870 972 3979"
web: em-bellis.github.io
#updated: no 

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

*Oregon State University, Corvallis, OR*, Ph.D., Integrative Biology \hfill{2017}

*Texas A&M University, College Station, TX*, B.S., Genetics & Biochemistry \hfill 2010

# APPOINTMENTS

*Arkansas State University, Jonesboro, AR:*

 > Associate Director, Center for No-Boundary Thinking \hfill{01/2020--Present}
 > Division Lead, CNBT Division of Biological Systems \hfill{01/2020--Present}  
 > Assistant Professor of Bioinformatics \hfill{01/2020--Present}   
 > Research Assistant Professor of Bioinformatics \hfill{10/2019--01/2020}  
 
*The Pennsylvania State University, State College, PA:*  

 > NSF Nat'l Plant Genome Postdoctoral Research Fellow \hfill{01/2018--09/2019}  

*Reed College, Portland, OR:*  

 > Postdoctoral Research Associate in Genomics \hfill{07/2017--12/2017}    
 
# RESEARCH INTERESTS  
Genomic basis of genotype-phenotype-environment interactions; machine learning and data science for biological and agricultural systems; analysis of biological data with high spatiotemporal complexity    

# PUBLICATIONS
## Peer-reviewed
1. **E.S. Bellis**, R.D. Lucardi, K. Saltonstall, T.D. Marsico. Predicting invasion risk of grasses under climate change requires improved genomic understanding of adaptive potential. *American Journal of Botany.* Accepted. 

1. **E.S. Bellis\***, A.A. Hashem\*, J.L. Causey, B.R.K. Runkle, B. Moreno-García, B. Burns, V.S. Green, T.N. Burcham, M.L. Reba and X. Huang (2022). Detecting intra-field variation in rice yield with UAV imagery and deep learning. *Frontiers in Plant Science* 13: 716506.  \*co-first authors.

1. **E.S. Bellis\***, C.M. McLaughlin\*, C.W. dePamphilis, & J.R. Lasky (2021). The geography of parasite local adaptation to host communities. *Ecography* 44: 1-13. \*co-first authors.  

16. E.K.H. Ho\*, **E.S. Bellis\***, J. Calkins, J.R. Adrion, L.C. Latta IV, S. Schaack (2021). Engines of change: Transposable element mutation rates are high and vary widely among genotypes and populations of *Daphnia magna. PLoS Genetics* 17: e1009827. \*co-first authors.

17. J. Masanga, R. Oduor, A. Alakonya, M. Ngugi, P. Ojola, **E.S. Bellis\***, and Steven Runo\* (2021). Comparative phylogeographic analysis of *Cuscuta campestris* and *C. reflexa* in Kenya: implications for management of highly invasive vines. *Plants, People, & Planet* 4: 182-193. \*corresponding authors.

1. J. Masanga, B. N. Mwangi, W. Kibet, M. Wamalwa, P. Sagero, R. Oduor, M. Ngugi, A. Alakonya, P. Ojola, **E. Bellis\***, S. Runo\* (2021). Physiological and ecological warnings that Dodder pose an exigent threat to farmlands in Eastern Africa. *Plant Physiology* 0: 1-11. \*senior authors.

6. **E.S. Bellis**, E.A. Kelly, C.M. Lorts, H. Gao, V.L. Deleo, G. Rouhan, A. Budden, G.B. Bhaskara, Z. Hu, R. Muscarella, M.P. Timko, B. Nebie, S.M. Runo, N.D. Chilcoat, T.E. Juenger, G.P. Morris, C.W. dePamphilis, and J.R. Lasky (2020). Genomics of sorghum local adaptation to a parasitic plant. *PNAS* 117: 4243-4251.  

5. R.M. Gutaker, S.C. Groen, **E.S. Bellis**, J.Y. Choi, I.S. Pires, R.K. Bocinsky, E. Slayton, O. Wilkins, C.C. Castillo, S. Negrao, M.M. Oliveira, D.Q. Fuller, J.A. d’Alpoim Guedes, J.R. Lasky, and M.D. Purugganan (2020). Genomic history and ecology of the geographic spread of rice. *Nature Plants* 6: 492-502.  

1. J. Stubblefield, M. Hervert, J. Causey, J. Qualls, W. Dong, L. Cai, J. Fowler, **E. Bellis**, K. Walker, J.H. Moore, S. Nehring, X. Huang (2020). Cardiac or Infectious? Transfer Learning with Chest X-Rays for ER Patient Classification.  *Scientific Reports* 10: 20900.  

1. R.D. Lucardi, **E.S. Bellis**, C.E. Cunard, J.K. Gravesande, S.C. Hughes, L.E. Whitehurst, S.J. Worthy, K.S. Burgess, T.D. Marsico (2020). Seeds attached to refrigerated shipping containers represent a substantial risk of nonnative plant species introduction and establishment. *Scientific Reports* 10: 15017.

2. L. Lopez, K. Turner, **E.S. Bellis**, & J.R. Lasky (2020). Genomics of natural history collections for understanding evolution in the wild. *Molecular Ecology Resources* 20: 1153-1160.

3. J.S. Shaver, **E.S. Bellis**, C. Iwaki, J. Qualls, J. Randolph, & J. Smith (2020). Massard prairie restoration and soil microbiome succession. *Journal of the Arkansas Academy of Science.*

4. M. Staton, C. Addo-Quaye, [and 29 others including **E.S. Bellis**] (2020). A reference genome assembly and adaptive trait analysis of *Castanea mollissima* 'Vanuxem', a source of resistance to chestnut blight in restoration breeding. *Tree Genetics & Genomes* 16: 57. 

7. L. Lopez, **E.S. Bellis**, E. Wafula, S. Hearne, L. Honaas, P. Ralph, N. Unachukwu, C.W. dePamphilis, and J.R. Lasky (2019). Transcriptomics of host-specific interactions in natural populations of the parasitic plant *Striga hermonthica. Weed Science* 67: 397-411.  

8. **E.S. Bellis**, R.B. Edlund^[Oregon State undergraduate mentee], H.K. Berrios, H.A. Lessios, and D.R. Denver (2018). Molecular signatures of host specificity linked to habitat specialization in a symbiotic sea anemone. *Ecology & Evolution* 8: 5413-5426.

9. **E.S. Bellis** and D. R. Denver (2017). Natural variation in responses to acute heat and cold stress in a sea anemone model system for coral bleaching. *Biological Bulletin* 233: 168-181. \**Cover article.*  

10. **E.S. Bellis**, D.K. Howe, and D.R. Denver (2016). Genome-wide polymorphism and signatures of selection in the symbiotic sea anemone *Aiptasia. BMC Genomics* 17: 160.

11. W.S. Phillips, A.L. Coleman-Hulbert, **E.S. Weiss**, D.K. Howe, S. Ping, R.I. Wernick, S. Estes, and D.R. Denver (2015). Selfish mitochondrial DNA proliferates in small, but not large, experimental populations of *Caenorhabditis briggsae. Genome Biology and Evolution* 7: 2023-2037.

12. A. Emblem, S. Okkenhaug, **E.S. Weiss**, D.R. Denver, B.O. Karlsen, T. Moum, and S.D. Johansen (2014). Sea anemones possess dynamic mitogenome structures. *Molecular Phylogenetics and Evolution* 75: 184-193.  

## Preprints/submitted 
20. S. Mutinda, F.M. Maati, B. Hale, O. Dayou, E. Ateka, A. Wijeratne, S. Wicke, **E.S. Bellis**, S.M. Runo. Resolving intergenotypic *Striga* resistance in sorghum.  *submitted.* 

20. I. Gilles, S. Mutinda, F. Mobegi, B. Hale, G. Omwenga, A. Wijeratne, S. Wicke, **E.S. Bellis**, and S.M. Runo. A transcriptome atlas of *Striga hermonthica* germination. *submitted.*

20. **E.S. Bellis**, C.S. von Münchow, C.O. Odero, A. Kronberger^[A-State undergraduate mentee], E. Kelly, T. Xia^[Penn State undergraduate mentee], X. Huang, S. Wicke, S.M. Runo, C.W. dePamphilis, J.R. Lasky. Genomic signatures of host-specific selection in a parasitic plant. *bioRxiv.*

19. C. Yim^[Penn State undergraduate mentee], **E.S. Bellis**, V.L. DeLeo, D. Gamba, R. Muscarella, and J.R. Lasky. Climate biogeography of Arabidopsis thaliana: linking distribution models, individual performance, and life history. *submitted.*


# RESEARCH GRANTS  
## National
>NSF NRT-URoL: UandI-DEECoDE: Understanding Invasion and Disease Ecology and Evolution through Computational Data Education ($1,999,484; role: co-PI) \hfill{2022-2026}

>US-AID PEER Program Grant: Deploying *Striga* Smart Sorghum: The last mile ($75,000; PI: S.M. Runo; US-supported partner: Bellis)  \hfill{2020-2021}  

>Coral Reef Alliance Coral Adaptation Challenge Grant ($18,000; role: PI) \hfill{2016}

## Regional
>Arkansas NSF EPSCoR DART Seed Grant: AgAdapt: An evolutionarily-informed algorithm for genomic prediction of crop performance in novel environments ($89,296; role: PI) \hfill{2022-2023}

>USDA Forest Service-Southern Research Station Joint Venture Agreement: Estimating invasive plant propagule pressure and modeled establishment risk to Southern agroforestry ($193,776; role: co-PI) \hfill{2021-2026}

>Arkansas Biosciences Institute Seed Grant: "Correlating environmental microbial diversity to prevalence and severity of an emerging vertebrate disease" ($69,609; role: co-PI) \hfill{2021-2023}

>Arkansas INBRE Collaborative Research Grant: "Effect of Soil Microbiome Succession on the Prevalence of Antibiotic Resistance" ($51,446; role: PI) \hfill{2020}

>Arkansas INBRE Core Facility Voucher Award ($5,000; role: PI) \hfill{2020}

## Submitted/Pending
>USDA NIFA AFRI: Machine learning integration of multitemporal imagery and genomics to accelerate development of climate-smart rice ($297,976; submitted; role: PI) \hfill{2022}  

<!-- >NSF BRC-BIO: The Coevolutionary Maintenance of Genomic Variation in Complex Systems ($499,635; submitted; role: PI) \hfill{2022}   -->

<!-- >NSF MRI Track I Acquisition: Arkansas HPC-A Reconfigurable Computer System for Research and Acquisition ($699,762; submitted; role: co-PI) \hfill{2022}   -->

<!-- >NSF EPSCoR RII Track-2: Artificial Intelligence for Plant Systems Science through EPSCoR AI-Campus towards Industries of Tomorrow ($5,000,000; submitted; role: co-PI) \hfill{2022}   -->

<!-- >US Fish & Wildlife Service: Preventing landscape-level invasion by employing early detection and rapid response of nonnative weed species hitchhiking via global trade routes ($1,056,990; not funded; PI: Travis Marsico, co-PIs: E. S. Bellis, Rima Lucardi, K. Saltonstall) \hfill{2022}  -->

<!-- >USDA Forest Service Southern Research Station submission to Bipartisan Infrastructure Investment and Jobs Act: Early detection and rapid response to minimize risk from hitchhiking nonnative species via global trade routes ($3,141,849; A-State subaward: $1,868,106; not funded), PI: R. D. Lucardi, Co-PIs: **E. S. Bellis,** T. D. Marsico, K. Saltonstall, J. H. Leebens-Mack \hfill{2022} -->

<!-- >USDA NIFA AFRI: Quantifying Risk To Agroforestry From Hitchhiking Nonnative Species Via Global Trade Routes ($749,780; not funded; role: co-PI) \hfill{2021} -->

<!-- >NSF EPSCoR RII Track-2: Artificial Intelligence for Plant Systems Science through EPSCoR AI-Campus ($5,076,668; not funded; role: co-PI) \hfill{2021} -->

<!-- >NIH R35: Understanding the genotype-phenotype-environment nexus with ensemble learning ($1,378,720; not funded; role: PI) \hfill{2020} -->

<!-- >NSF EPSCoR RII Track-2: Connecting Artificial Intelligence and Plant Biology to Understand Adaptation to Environment ($4,683,896; not funded; role: co-PI)  -->
<!--   \hfill{2020} -->

# FELLOWSHIPS & AWARDS  
## National  
>Ecological Society of America NEON Early Career Scholar ($1,500) \hfill{2020}  

>NSF Postdoctoral Research Fellowship in Biology ($207,000) \hfill{2017}   

>Society for Integrative & Comparative Biology Libbie H. Hyman Memorial Scholarship ($1,500; declined) \hfill{2013}   

>NSF Graduate Research Fellowship ($121,000) \hfill{2011}  

>National Merit Scholarship ($2,500) \hfill{2006}  

## Regional  
> Arkansas Biosciences Institute New Investigator of the Year [(press)](https://aaes.uada.edu/news/emily-bellis-abi-researcher/) \hfill{2022}  

>Oregon State University Paul & Mary Roberts Fellowship for the Study of Evolution ($2,500) \hfill{2017}  

>University of Washington Summer Institute Scholarship ($900) \hfill{2016}  

>Smithsonian Tropical Research Institute Short Term Fellowship ($3,000) \hfill{2014}  

>Oregon State University Provost’s Distinguished Fellowship ($30,000) \hfill{2011}  

>Texas A&M University President’s Endowed Scholarship, National Merit Recognition Award, Director's Excellence Award, and Non-Resident Tuition Waiver ($75,000) \hfill{2006}

# INVITED TALKS  
University of Arkansas, Entomology and Plant Pathology Seminar Series, Fayetteville, AR, Jan. 24 \hfill{2023}  

Missouri State University, Biology Seminar Series, Springfield, MO, Oct. 21 \hfill{2022} 

Boyce Thompson Institute PGS Annual Symposium, Ithaca, NY, Sep. 16 \hfill{2022} 

16th World Congress on Parasitic Plants, Nairobi, Kenya, July 7 (keynote) \hfill{2022}  

Idaho State University, Pocatello, ID, Mar. 17 \hfill{2022}  

International Parasitic Plant Society Seminar Series, remote, Dec. 1 \hfill{2021}  

California State University, San Bernadino Biology Department Seminar Series, remote, Nov. 19 \hfill{2021}  

[Loop Genomics Webinar Series](https://www.loopgenomics.com/post/webinar-effect-of-tallgrass-prairie-restoration-and-soil-microbiome-succession-on-the-prevalence-of), remote, May 12 \hfill{2021}    

Penn State Center for Parasitic & Carnivorous Plants, remote, Aug. 20  \hfill{2020}  

University of Memphis Earth Sciences Colloquium Series, Memphis, TN, April 17 (*cancelled due to COVID-19*) \hfill{2020}  

University of Arkansas Fort Smith STEM Seminar, Fort Smith, AR, Feb. 14  \hfill{2020}  

The Pennsylvania State University Ecology Seminar, State College, PA , Sep. 13 \hfill{2019}  

NSF Plant Genome Research Program Awardee Meeting, Washington D.C., Sep. 4 \hfill{2019} 

Society of Herbarium Curators Annual Meeting, Tucson, AZ, Aug. 1 \hfill{2019}  

University of Arkansas for Medical Sciences Career Day, Little Rock, AR, Oct. 18  \hfill{2019}  

Workshop on Genomics Tools for *Striga* management, Nairobi, Kenya, June 22 \hfill{2018}  

Reed College Biology Department Seminar Series, Oct. 27 \hfill{2017}  

Coral Reef Alliance Adaptation Challenge Workshop, San Francisco, CA, April 17 \hfill{2017}  

# COURSES TAUGHT 
## Arkansas State University  
CS1094: Making Connections Computer Science (Fall 2022)  
CS1114: Concepts of Programming (including Honors section; Spring 2021)  
CS6823: Fundamentals of Machine Learning (cross-listed w/ MBS6251; Summer 2020, Spring 2022, Fall 2022, Spring 2023)   
DATA2004: Programming for Data Analytics (Spring 2023)  

## Oregon State University 
Z362: Invertebrate Biology Lab (Instructor) \hfill{Spring 2017}  
MCB525: Techniques in Molecular and Cellular Biology (Instructor)\hfill{Fall 2016}  
BI213: Principles of Biology (Curriculum Development Assistant)\hfill{Winter 2016}  
BI311: Genetics (Teaching Assistant)\hfill{Spring 2014}  
BI212: Principles of Biology Lab (Teaching Assistant)\hfill{Winter 2014}   
BI211: Principles of Biology Lab (Teaching Assistant)\hfill{Fall 2013} 

# STUDENT MENTORING 
## Arkansas State University
N. Haydt, Molecular Biosciences Doctoral Student  
  (co-advised w/L. Neuman-Lee)  \hfill {Aug. 2021--Present}  
I. Hughes, Biology M.S. Student  
  (co-advised w/T. Marsico)  \hfill {June 2022--Present}    
F. Farag, Computer Science M.S. Student  
  (co-advised w/A. Hashem) \hfill{Aug. 2021--Present}  
Y. Wang, Undergraduate Researcher  \hfill {May 2022--Present}  
S. McCormick, Undergraduate Researcher \hfill{May 2021--Present}  
E. Soriano Chavez, Undergraduate Researcher \hfill{May 2020--Present}  
S. Tamang, Undergraduate Researcher  \hfill {April--Oct. 2022}  
D. Delgadillo, Undergraduate Researcher \hfill{May--Nov. 2021}  
A. Kronberger, Undergraduate Researcher  
  (co-advised w/X. Huang) \hfill{Oct. 2020--Aug. 2021}   
A. Le'Flore, Undergraduate Researcher \hfill{Oct. 2020--May 2021}   
S. Rutledge, Undergraduate Researcher \hfill{Jan.--Aug. 2020}  

## The Pennsylvania State University  
T. Xia, Undergraduate Researcher (now pursuing Ph.D. at UC Davis) \hfill{2019}  
C. Yim, Undergraduate Researcher \hfill{2018--2019}  

## Oregon State University  
E. Kramer, Undergraduate Researcher \hfill{2016--2017}  
R. Edlund, Undergraduate Researcher \hfill{2014--2016}  
A. Vercruyssen, Undergraduate Researcher \hfill{2013--2014}  
J. Seng, Undergraduate Researcher \hfill{2011--2014}  
B. VerWey, Undergraduate Researcher \hfill{2013} 

# PROFESSIONAL SERVICE (since 2018) 
## National/International
- Program committee member for 2021 and 2022 ACM Conference on Bioinformatics, Computational Biology, and Health Informatics  
- Facilitator for Bioinformatics Workshop at Kenyatta University, Kenya (delivered remotely due to COVID-19; 2020)  
- Review Editor for *Frontiers in Plant Science*  (2020 -- Present)  
- Panel Reviewer for the National Science Foundation (2020) and the Natural Sciences and Engineering Research Council of Canada (2022)     
- Manuscript Reviewer for *Agronomy* (2020), *American Society of Agricultural and Biological Engineers* (2020, 2021), *Ecology Letters* (2020), *IEEE/ACM Transactions on Computational Biology and Bioinformatics* (2020, 2021), *Plant Physiology* (2020), *The Plant Journal* (2019, 2020), *Marine Biology* (2019), *Molecular Ecology Resources* (2020), *Nature Biotechnology* (2021, 2022)    
- Guest Editor for *Molecular Ecology Resources* special issue (2020)  

## Regional 
- Led coding activity for 13 participants (age 12-15) in the Museum of Discovery Girls in STEM program (summer 2021)  
- Led 'Spatial Data in R' session for Arkansas Summer Research Institute 2021 and 'Intermediate Feature Selection' in 2022   
- Team coach for Arkansas AI-Campus, a hands-on training program to provide skills in machine learning to students and professionals in AR (2020, 2021)  
- Member of the Scientific Program Committee for Arkansas Bioinformatic Consortium 2020 Meeting: Artificial Intelligence in Arkansas   
- Invited speaker for ~1hr session on Individual Development Plans for Graduate Student Professional Development workshop at the annual faculty and student Center for Advanced Surface Engineering (CASE) Retreat in Petit Jean, AR (Jan. 10).  Event attended by ~30 graduate students from five Arkansas institutions 

## Institutional  
- Co-organizer of the [A-State R User Group](https://a-state-ruser.readthedocs.io/en/latest/) (2020 -- Present)  
- MBS Admissions Committee (2021 -- Present)  
- Service on Advisory Committee for three Ph.D. students and one M.S. student in the Molecular Biosciences program (J. Stubblefield, 2019 -- 2021; J. Fowler, 2020 -- 2023; L. Martin, 2020 -- 2021; and B. Hale, 2020 -- Present)  
- Service on Advisory Committee for one M.S. student in Biology (B. Kosnik, 2021 -- Present)  
- Service on Advisory Committee for one M.S. student and one undergraduate honors student in the Computer Sciences program (S. Singh, 2021; C. Seglem, 2021 -- 2022)  

<!-- # PROFESSIONAL DEVELOPMENT   -->
<!-- ## Research  -->
<!-- Botany 2019 Workshop: Using Digitized Herbarium Data in Research   -->
<!-- University of Washington Summer Institute 2016 (Bayesian Statistics for Genetics, MCMC for Genetics) -->

<!-- ## Teaching  -->
<!-- CIRTL (Center for the Integration of Research, Teaching and Learning) Certification, Associate Level   -->
<!-- Completed 12 credit hours of graduate level coursework in teaching and learning theory, course design and methods, inclusivity training, and science communication   -->
